// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FolderItem = { id: bigint, name: string, parent_id: bigint | null, children_count: bigint, updated_at: string, };
