// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MutationResult<T> = { success: boolean, message: string, data: T | null, error: string | null, };
