// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Note = { id: bigint, title: string, body: string, folder_id: bigint | null, tags: string, sort_order: bigint, parent_note_id: bigint | null, is_pinned: boolean, is_favorite: boolean, word_count: bigint, mood: string, created_at: string, updated_at: string, };
