// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NoteItem = { id: bigint, title: string, folder_id: bigint | null, parent_note_id: bigint | null, is_pinned: boolean, is_favorite: boolean, word_count: bigint, updated_at: string, };
